apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: test
  name: express-hw
  namespace: ns-ignite.dev-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-hw
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: express-hw
        env: test
    spec:
      containers:
        - image: stephanezang/express-hw:latest
          name: express-hw
          imagePullPolicy: Always
          resources:
            limits:
              memory: 250Mi
          readinessProbe:
            tcpSocket:
              port: 8008
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8008
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 15